baseURL: "https://www.indianeconomist.in/"
title: Indian Economist
paginate: 5
theme: PaperMod

markup:
  goldmark:
    renderer:
      unsafe: true


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: The Indian Economist
    description: "The place of for all kinds of Economics"
    keywords: [Marketing, Economics, Indian Economics, Digital Marketing]
    author: 
    # author: ["Me", "You"] # multiple authors
    images: ["Economics.jpg"]
    DateFormat: "January 2, 2006"
    defaultTheme:  dark #auto, light
    disableThemeToggle: false

    ShowReadingTime: false
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    assets:
      favicon: favicon/favicon.ico
      favicon16x16: favicon/favicon-16x16.png
      favicon32x32: favicon/favicon-32x32.png
      apple_touch_icon: favicon/apple-touch-icon.png
      android-chrome: favicon/android-chrome-512x512.png


    label:
        text: "The Indian Economist"
        icon: /favicon/apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hello there 👋"
        Content: |
          - Welcome to my site! Having completed my Honors in Economics and while completing my MA in Digital Marketing and Social Media, I started learning programming.
          -
          - What sarted as a journey to help myself set up analytics code on business sites, ended up with me detailing everything out that I learn along the way, which I can reference to later.
          -
          - So go ahead, dive in and help yourself with whatever you can!

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/sagarkapr/"
        - name: github
          url: "https://github.com/sagar-kap"
        - name: twitter
          url: "https://twitter.com/SagarKapr" 
        - name: stackoverflow 
          url: "https://stackoverflow.com/users/14096244/sagar-kapoor"


    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page

    #editPost:
        #URL: "https://github.com/<path_to_repo>/content"
        #Text: "Suggest Changes" # edit text
        #appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: about
          name: About
          url: /about/
          weight: 10
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 20
        - identifier: WebDev
          name: WebDev
          url: https://www.sagarkapoor.eu/
          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai